"""Export the abbreviation dictionary to text-expander apps.

Type a short trigger (``;htn`` by default) anywhere on the machine and the
expander types the full term. Supported formats:

* ``plist`` — macOS Text Replacements (drag the file into System Settings →
  Keyboard → Text Replacements).
* ``espanso`` — an Espanso match file (``match/chartcleaner.yml``).
* ``textexpander`` — TextExpander CSV import (abbreviation, content, label).
* ``ahk`` — AutoHotkey v2 hotstrings for Windows.

Do Not Use abbreviations are skipped by default (see abbreviation_safety).
"""

from __future__ import annotations

import csv
import io
import json
import plistlib
import re

from .abbreviation_safety import _bundled_pairs, is_blocked
from .abbreviations import normalize_settings

__all__ = ["FORMATS", "EXTENSIONS", "entries", "render", "export_filename"]

FORMATS = ("plist", "espanso", "textexpander", "ahk")
EXTENSIONS = {"plist": "plist", "espanso": "yml", "textexpander": "csv", "ahk": "ahk"}
_PARENTHETICAL = re.compile(r"\s+\([^()]*\)$")


def _expansion(term: str) -> str:
    """The text to type: first alternative, no trailing explanation."""
    text = _PARENTHETICAL.sub("", term.split(" / ")[0]).strip()
    # Sentence-case dictionary entries ("Hypertension") read wrong mid-sentence.
    # Only plain words ("Hypertension"), not codes like "A1 segment".
    if (len(text) > 1 and text[0].isupper() and text[1].islower()
            and not any(c.isupper() for c in text[1:])):
        text = text[0].lower() + text[1:]
    return text


def entries(cfg: dict | None = None, *, prefix: str = ";", include_bundled: bool = True,
            skip_unsafe: bool = True) -> list[tuple[str, str]]:
    """``(trigger, expansion)`` pairs; custom entries win over bundled ones."""
    group = normalize_settings((cfg or {}).get("abbreviations") if isinstance(cfg, dict) else {})
    disabled = {t.casefold() for t in group["disabled"]}
    candidates: list[tuple[str, str, bool]] = [
        (c["replacement"], c["term"], bool(c.get("acknowledged")))
        for c in group["custom"] if c.get("enabled", True)]
    if include_bundled:
        custom_terms = {c["term"].casefold() for c in group["custom"]}
        candidates += [(abbr, term, False) for term, abbr in _bundled_pairs()
                       if term.casefold() not in disabled and term.casefold() not in custom_terms]
    out: dict[str, str] = {}
    for abbr, term, acknowledged in candidates:
        if len(abbr) < 2 or any(c.isspace() for c in abbr):
            continue  # single letters and multi-word shorthands make poor triggers
        if skip_unsafe and not acknowledged and is_blocked(abbr, term):
            continue
        trigger = prefix + abbr.casefold()
        expansion = _expansion(term)
        if expansion and trigger not in out:
            out[trigger] = expansion
    return sorted(out.items())


def _yaml_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)  # JSON strings are valid YAML


def _ahk_escape(value: str) -> str:
    return value.replace("`", "``").replace(";", "`;")


def render(fmt: str, pairs: list[tuple[str, str]]) -> bytes:
    if fmt == "plist":
        return plistlib.dumps([{"phrase": exp, "shortcut": trig} for trig, exp in pairs])
    if fmt == "espanso":
        lines = ["# Generated by Chart Cleaner — medical abbreviation expansions", "matches:"]
        for trig, exp in pairs:
            lines += [f"  - trigger: {_yaml_str(trig)}", f"    replace: {_yaml_str(exp)}",
                      "    propagate_case: true"]
        return ("\n".join(lines) + "\n").encode("utf-8")
    if fmt == "textexpander":
        buf = io.StringIO()
        writer = csv.writer(buf, lineterminator="\n")
        for trig, exp in pairs:
            writer.writerow([trig, exp, f"Chart Cleaner: {exp}"])
        return buf.getvalue().encode("utf-8")
    if fmt == "ahk":
        lines = ["; Generated by Chart Cleaner — medical abbreviation expansions (AutoHotkey v2)",
                 "#Requires AutoHotkey v2.0", ""]
        # A colon or backtick in the trigger would break the hotstring; skip those.
        lines += [f":T:{trig}::{_ahk_escape(exp)}" for trig, exp in pairs
                  if ":" not in trig and "`" not in trig]
        return ("\n".join(lines) + "\n").encode("utf-8")
    raise ValueError(f"Unknown format {fmt!r}; expected one of {', '.join(FORMATS)}")


def export_filename(fmt: str) -> str:
    if fmt == "espanso":
        return "chartcleaner.yml"
    return f"chartcleaner-abbreviations.{EXTENSIONS[fmt]}"
